export interface Band {
  id: string;
  name: string;
  isNewAddition?: boolean;
}

export const BILLBOARD_BANDS: Band[] = [
  { id: '1', name: 'The Beatles' },
  { id: '2', name: 'The Rolling Stones' },
  { id: '3', name: 'Led Zeppelin' },
  { id: '4', name: 'Pink Floyd' },
  { id: '5', name: 'Queen' },
  { id: '6', name: 'Fleetwood Mac' },
  { id: '7', name: 'U2' },
  { id: '8', name: 'Sly & The Family Stone' },
  { id: '9', name: 'Black Sabbath' },
  { id: '10', name: 'Nirvana' },
  { id: '11', name: 'The Who' },
  { id: '12', name: 'Metallica' },
  { id: '13', name: 'AC/DC' },
  { id: '14', name: 'Creedence Clearwater Revival' },
  { id: '15', name: 'Talking Heads' },
  { id: '16', name: 'The Grateful Dead' },
  { id: '17', name: 'Heart' },
  { id: '18', name: 'The Clash' },
  { id: '19', name: 'The Beach Boys' },
  { id: '20', name: 'Radiohead' },
  { id: '21', name: 'Van Halen' },
  { id: '22', name: 'Rage Against the Machine' },
  { id: '23', name: "Guns N' Roses" },
  { id: '24', name: 'The Velvet Underground' },
  { id: '25', name: 'Maná' },
  { id: '26', name: 'Pretenders' },
  { id: '27', name: 'Parliament/Funkadelic' },
  { id: '28', name: 'The Allman Brothers Band' },
  { id: '29', name: 'R.E.M.' },
  { id: '30', name: 'Pearl Jam' },
  { id: '31', name: 'Paramore' },
  { id: '32', name: 'Aerosmith' },
  { id: '33', name: 'The White Stripes' },
  { id: '34', name: 'Nine Inch Nails' },
  { id: '35', name: 'Eagles' },
  { id: '36', name: 'Ramones' },
  { id: '37', name: 'Thin Lizzy' },
  { id: '38', name: 'Santana' },
  { id: '39', name: 'Green Day' },
  { id: '40', name: 'Blondie' },
  { id: '41', name: 'The Band' },
  { id: '42', name: 'Earth, Wind & Fire' },
  { id: '43', name: 'No Doubt' },
  { id: '44', name: 'Cafe Tacvba' },
  { id: '45', name: 'The Stooges' },
  { id: '46', name: 'Oasis' },
  { id: '47', name: 'Def Leppard' },
  { id: '48', name: 'Sleater-Kinney' },
  { id: '49', name: 'The Cure' },
  { id: '50', name: 'Red Hot Chili Peppers' },
];
